### ISSUE TITLE
Can't run on Arch New Install

### ISSUE THREAD

**Issue by hanami117** [dfaker/WebmGenerator#114]
Hello @dfaker I did the following passages

>  cd into the webmgenerator folder
> 
> make a virtual environment https://wiki.archlinux.org/title/Python/Virtual_environment
> 
> python -m venv envname
> 
> then activate environment with
> 
> source envname/bin/activate
> 
> then
> 
> pip install -r requirements-linux.txt
> 
> then run it with
> 
> python webmGenerator.py

And when I do python webmGenerator.py this is what I get:
```
`envname) [beki@archlinux WebmGenerator]$ python webmGenerator.py
Initial working directory /home/beki/WebmGenerator
Current working directory /home/beki/WebmGenerator
2024-09-11 16:26:01,403 [MainThread  ] [INFO ]  Startup.
/home/beki/WebmGenerator/src
/home/beki/WebmGenerator/envname/bin
module 'os' has no attribute 'add_dll_directory'
2024-09-11 16:26:01,404 [MainThread  ] [ERROR]  Startup Exception
Traceback (most recent call last):
  File "/home/beki/WebmGenerator/webmGenerator.py", line 29, in <module>
    from src.webmGeneratorController import WebmGeneratorController
  File "/home/beki/WebmGenerator/src/webmGeneratorController.py", line 27, in <module>
    from tkinter import Tk
  File "/usr/lib/python3.12/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
2024-09-11 16:26:01,407 [MainThread  ] [ERROR]  Traceback (most recent call last):
  File "/home/beki/WebmGenerator/webmGenerator.py", line 29, in <module>
    from src.webmGeneratorController import WebmGeneratorController
  File "/home/beki/WebmGenerator/src/webmGeneratorController.py", line 27, in <module>
    from tkinter import Tk
  File "/usr/lib/python3.12/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory

2024-09-11 16:26:01,408 [MainThread  ] [INFO ]  DONE
`
```
This is on the latest pull of webmGenerator

**Comment by hanami117** [comment]
```
(envname) [beki@archlinux WebmGenerator-3.42.0]$ python webmGenerator.py
Initial working directory /home/beki/WebmGenerator-3.42.0
Current working directory /home/beki/WebmGenerator-3.42.0
2024-09-11 16:30:38,385 [MainThread  ] [INFO ]  Startup.
/home/beki/WebmGenerator-3.42.0/src
/home/beki/WebmGenerator-3.42.0/envname/bin
module 'os' has no attribute 'add_dll_directory'
2024-09-11 16:30:38,394 [MainThread  ] [ERROR]  Startup Exception
Traceback (most recent call last):
  File "/home/beki/WebmGenerator-3.42.0/webmGenerator.py", line 29, in <module>
    from src.webmGeneratorController import WebmGeneratorController
  File "/home/beki/WebmGenerator-3.42.0/src/webmGeneratorController.py", line 27, in <module>
    from tkinter import Tk
  File "/usr/lib/python3.12/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
2024-09-11 16:30:38,396 [MainThread  ] [ERROR]  Traceback (most recent call last):
  File "/home/beki/WebmGenerator-3.42.0/webmGenerator.py", line 29, in <module>
    from src.webmGeneratorController import WebmGeneratorController
  File "/home/beki/WebmGenerator-3.42.0/src/webmGeneratorController.py", line 27, in <module>
    from tkinter import Tk
  File "/usr/lib/python3.12/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory

2024-09-11 16:30:38,396 [MainThread  ] [INFO ]  DONE
(envname) [beki@archlinux WebmGenerator-3.42.0]$ 

```

Doesnt even work on 3.42.

**Comment by hanami117** [comment]
sudo pacman -S tk
